pipeline {
    agent any

    environment {
        SONARQUBE_SERVER = 'http://localhost:9001'
        SONARQUBE_TOKEN = 'squ_d2b13faf8b5a4741bd22192dbab2a11d9d6ad765'
    }

    stages {
              

        stage('Run SonarQube Analysis') {
            steps {
                script {
                    sh '/opt/gradle/gradle-8.1.1/bin/gradle -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.host.url=$SONARQUBE_SERVER sonar'
                }
            }
        }
    }

    post {
        always {
            cleanWs() // Clean up workspace after build
        }
    }
}
