pipeline
{
  agent any
  environment {
        // Ensure the SonarQube scanner tool is available
        scannerHome = tool 'SonarqubeLocal' // 'SonarScanner' should match the tool name configured in Jenkins
    }
  stages
  {
  stage('Build')
    {
      steps{
           script {
                    withSonarQubeEnv('SonarqubeLocal') {  // Ensure 'Sonar' matches your SonarQube server name configured in Jenkins
                        sh "${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=projectKey \
                            -Dsonar.projectName=project-name \
                            -Dsonar.projectVersion=1 \
                            -Dsonar.sources=."
                    }
                }
           }
      
    }
  }
}
